### ISSUE TITLE
show float rather than integer

### ISSUE THREAD

**Issue by louieogrady** [hugozap/react-rotary-knob#13]
Hi, is there anyway to show floats rather than integers on the skins with numbers? I've tried using the Javascript toFixed() to get what I need but it doesn't seem to work. Any ideas?

**Comment by hugozap** [comment]
You can clone a skin file e.g https://github.com/hugozap/react-rotary-knob-skin-pack/blob/1e8e923c6583105c6e0e478c77b1ec31c610d207/skins/s17.js#L88 and change toFixed(decimals), that should work.
