### ISSUE TITLE
Visual helpers in wrong place when inside a translated element 

### ISSUE THREAD

**Issue by mbstrauss** [hugozap/react-rotary-knob#9]
Hi Hugo

I noticed something strange today. On the image I've uploaded, I was rotating the knob on the top left hand corner, but the visual helper was at the bottom of the screen and offset slightly to the right.  The knob was in a react-grid-layout element which can be dragged/moved using css transform/translate. 

When I manually removed the transform then the helper moved to the correct position on the knob.

Have you seen this before or have any idea what's causing it?

Thanks

Michael

PS I do like precision mode, excellent idea

![image](https://user-images.githubusercontent.com/37088449/52120214-b7e56400-266f-11e9-99e2-4722ee951893.png)

**Comment by hugozap** [comment]
Hi, I haven't tried it with react grid layout component.  Do you have a url
where I can take a look?

Not sure where it breaks right now but did you try adding a wrapper div to
the knob?

**Comment by mbstrauss** [comment]
I've created this https://codesandbox.io/embed/64qwznwvz3

It uses a react-draggable which is similar to react-grid-layout.

Drag the yellow area and the further you move from 0,0 the more the helper moves

**Comment by hugozap** [comment]
Awesome!

**Comment by hugozap** [comment]
@mbstrauss btw, for you application it may be a good idea to use a Limited Knob that doesn't allow jumps from min to max value. I just added it to the docs but here's the idea: https://codesandbox.io/s/qvyyyvv346

**Comment by mbstrauss** [comment]
Thank you for that, was scratching round on how to do it
